### ISSUE TITLE
Read-me comment

### ISSUE THREAD

**Issue by Onwa2014** [codex-academy/read-me#1]
@SteveBarnett I like the way the read me file is written I learnt a lot so it was also helpful for me as I am not good at writing a read-me file. I did not get the part about codeX docs Jekyll Skellington that is the fist page is that one of the example or we are not going to show that one to coders? I did not know where to comment so  I

**Comment by Onwa2014** [comment]
I thought I should create an issue.

**Comment by SteveBarnett** [comment]
@Onwa2014 Yes, the codeX docs Jekyll Skellington part is just for us: the coders won't see it.
Thanks for feedback!
